CREATE TABLE Person (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_OF_BIRTH DATE
);

CREATE TABLE Address (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STREET_NUMBER VARCHAR(255),
    STREET_NAME VARCHAR(255),
    TOWN VARCHAR(255),
    CITY VARCHAR(255),
    PROVINCE VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    	PERSON_ID BIGINT,
    FOREIGN KEY (PERSON_ID) REFERENCES Person(ID)
);
